grpc:
  client:
    UserDetailsService:
      address: static://localhost:9002
      negotiationType: plaintext
server:
  port: 8080

rest:
  UserDetailsService:
    service:
      endpoint: http://localhost:9001
